<h1>Element: <em><?php echo $modelElement->getName() ?></em></h1>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('wiss/model-element/properties', array($modelElement->getId())) ?>">Properties</a></li>
    <li class="active"><a href="<?php echo $this->url('wiss/model-element/config', array($modelElement->getId())) ?>">Configuration</a></li>
</ul>

<?php echo $this->formRenderer($form) ?>
