<h1><?php echo $model->getTitle() ?></h1>

<?php echo $this->navigation('cms')->menu()->setUlClass('nav nav-tabs')->renderSubmenu() ?>

<ul class="unstyled">
	<?php foreach($entities as $entity) : ?>
	<li>
		<h3><?php echo $model->buildLabel($entity) ?></h3>
		<dl>
			<a href="<?php echo $this->url($routeName . '/edit', array('id' => $entity->getId())) ?>" class="btn btn-primary btn-small">Edit</a>
			<a href="<?php echo $this->url($routeName . '/delete', array('id' => $entity->getId())) ?>" class="btn btn-small">Delete</a>
		</dl>
	</li>
	<?php endforeach ?>

</ul>

<div class="btn-group">
	<a href="<?php echo $this->url($routeName . '/create') ?>" class="btn btn-primary">Create new <?php echo $model->getTitle() ?></a>
	<a href="<?php echo $this->url('wiss/module/' . $module->getSlug() . '/models') ?>" class="btn">To <?php echo $module->getTitle() ?> module</a>
</div>