<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->prependStylesheet($this->basePath() . '/bootstrap/css/datepicker.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
                                  ->appendFile($this->basePath() . '/js/bootstrap.min.js')
//                                  ->appendFile($this->basePath() . '/js/bootstrap.alert.js')
                                  ->appendFile($this->basePath() . '/js/jstree/jquery.jstree.js')
                                  ->appendFile($this->basePath() . '/js/bootstrap/js/bootstrap-datepicker.js')
                                  ->appendFile($this->basePath() . '/js/site.js') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">CMS</a>
          <div class="nav-collapse">
            <?php echo $this->navigation('cms')->menu()->setMinDepth(0)->setMaxDepth(1)->setOnlyActiveBranch(false)->setUlClass('nav pills')->setPartial('navigation/menu') ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
		
	
		<div class="breadcrumbs"><?php echo $this->navigation('cms')->breadcrumbs() ?></div>
      
		<?php if($this->flashMessenger()->hasMessages()) : ?>
		<div class="messages">			
			<?php foreach($this->flashMessenger()->getMessages() as $message) : ?>
				<div class="alert"><?= $message ?></div>
			<?php endforeach ?>
		</div>
		<?php endif ?>
						
      <?php echo $this->content; ?>

      <hr>

      <footer>
		  
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
