<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
	<base href="<?php echo $this->basePath() ?>" />
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/compiled.css') ?>
	<?php echo $this->headScript()->appendFile($this->basePath() . '/js/compiled.js') ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('wiss') ?>">CMS</a>
          <div class="nav-collapse">
            <?php echo $this->navigation('cms')->menu()->setMinDepth(1)
                                                       ->setMaxDepth(2)
                                                       ->setOnlyActiveBranch(false)
                                                       ->setUlClass('nav pills')
                                                       ->setPartial('wiss/navigation/menu') ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
		
	
		<div class="breadcrumbs row"><?php echo $this->navigation('cms')->breadcrumbs() ?></div>
      
		<?php if($this->flashMessenger()->hasMessages()) : ?>
		<div class="messages row">			
			<?php foreach($this->flashMessenger()->getMessages() as $message) : ?>
				<div class="alert"><?php echo $message ?></div>
			<?php endforeach ?>
		</div>
		<?php endif ?>
						
        <div class="row">
            <content class="span9"><?php echo $this->content; ?></content>
            <sidebar class="span3"><?php echo $this->sidebar; ?></sidebar>            
        </div>
      

      <hr>

      <footer class="row"><?php echo $this->footer; ?></footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
