<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
	<base href="<?php echo $this->basePath() ?>/" />
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php
//	echo $this->plugin('HeadLink');
	
//	echo $this->plugin('HeadStyle');
//	echo $this->plugin('HeadScript');
//	echo $this->plugin('InlineScript');
	?>
	<script type="text/javascript" src="assets/wiss_js.js?1346417280"></script>
	<link type="text/css" rel="stylesheet" media="screen" href="assets/wiss_css.css?1346417280">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>


  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('wiss') ?>">CMS</a>
          <div class="nav-collapse">
            <?php echo $this->navigation('cms')->menu()->setMinDepth(1)
                                                       ->setMaxDepth(2)
                                                       ->setOnlyActiveBranch(false)
                                                       ->setUlClass('nav pills')
                                                       ->setPartial('wiss/navigation/menu') ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
		
	
		<div class="breadcrumbs"><?php echo $this->navigation('cms')->breadcrumbs() ?></div>
      
		<?php if($this->flashMessenger()->hasMessages()) : ?>
		<div class="messages">			
			<?php foreach($this->flashMessenger()->getMessages() as $message) : ?>
				<div class="alert"><?= $message ?></div>
			<?php endforeach ?>
		</div>
		<?php endif ?>
						
      <?php echo $this->content; ?>

      <hr>

      <footer>
		  
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
