<h1><?php echo $page->getTitle() ?></h1>

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('wiss/page/properties', array('id' => $page->getId())) ?>">Properties</a></li>
	<li><a href="<?php echo $this->url('wiss/page/route', array('id' => $page->getId())) ?>">Route</a></li>
	<li class="active"><a href="<?php echo $this->url('wiss/page/content', array('id' => $page->getId())) ?>">Content</a></li>
</ul>

<?php foreach($zones as $zone) : ?>

<h2><?php echo $zone->getTitle() ?></h2>
<ul class="list blocks blocks-used sortable unstyled" data-zone-id="<?php echo $zone->getId() ?>" data-sort-url="<?php echo $this->url('wiss/page/sort', array('id' => $page->getId())) ?>">
	<?php foreach ($used[$zone->getId()] as $content) : ?>
	<li class="block <?php if($content->isGlobal()) : ?> global<?php endif ?>" data-content-id="<?php echo $content->getId() ?>">
		<h2><?php echo $content->getTitle() ?></h2>
        <?php echo $this->partial('wiss/page/partial/content-actions.phtml', array('content' => $content)) ?>
	</li>
	<?php endforeach ?>
</ul>

<?php endforeach; ?>