<h1><?php echo $page->getTitle() ?></h1>

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('wiss/page/properties', array('id' => $page->getId())) ?>">Properties</a></li>
	<li><a href="<?php echo $this->url('wiss/page/route', array('id' => $page->getId())) ?>">Route</a></li>
	<li class="active"><a href="<?php echo $this->url('wiss/page/content', array('id' => $page->getId())) ?>">Content</a></li>
</ul>

<?php foreach($zones as $zone) : ?>

<h2><?php echo $zone->getTitle() ?></h2>
<ul class="list blocks blocks-used sortable unstyled" data-sort-url="<?php echo $this->url('wiss/page/sort', array('id' => $page->getId())) ?>">
	<?php foreach ($used[$zone->getId()] as $content) : ?>
	<li class="block" data-content-id="<?php echo $content->getId() ?>">
		<h2><?php echo $content->getTitle() ?></h2>
		<div class="btn-group">
            <?php if($content->getBlock()->getFormClass()) : ?>
			<a href="<?php echo $this->url('wiss/content/configuration', array('id' => $content->getId())) ?>" class="btn btn-small btn-primary">Configuration</a>
            <?php endif ?>
			<a href="<?php echo $this->url('wiss/content/properties', array('id' => $content->getId())) ?>" class="btn btn-small">Properties</a>
			<a href="<?php echo $this->url('wiss/content/delete', array('id' => $content->getId())) ?>" class="btn btn-small">Remove</a>
		</div>
	</li>
	<?php endforeach ?>
</ul>

<?php endforeach; ?>