<h1><?php echo $page->getTitle() ?></h1>

<ul class="nav nav-tabs">
	<li><a href="<?php echo $this->url('wiss/page/properties', array('id' => $page->getId())) ?>">Properties</a></li>
	<li class="active"><a href="<?php echo $this->url('wiss/page/content', array('id' => $page->getId())) ?>">Content</a></li>
</ul>

<?php foreach($zones as $zone) : ?>

<h2><?php echo $zone->getTitle() ?></h2>
<ul class="list blocks unstyled">
	<?php foreach ($used[$zone->getId()] as $content) : ?>
	<li class="block rounded-small">
		<h2><?php echo $content->getTitle() ?></h2>
		<div class="btn-group">
            <?php if($content->getBlock()->getFormClass()) : ?>
			<a href="<?php echo $this->url('wiss/page-content/configuration', array('id' => $content->getId())) ?>" class="btn btn-small btn-primary">Configuration</a>
            <?php endif ?>
			<a href="<?php echo $this->url('wiss/page-content/delete', array('id' => $content->getId())) ?>" class="btn btn-small">Remove</a>
		</div>
	</li>
	<?php endforeach ?>
	<li class="block rounded-small empty">
		Drag blocks in here...
	</li>
</ul>

<?php endforeach; ?>
