
<h1>Pages</h1>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/page/create') ?>" class="btn btn-large btn-primary">Create new page</a>
</div>

<ul class="unstyled list">
	<?php foreach($pages as $page) : ?>
	<li>
		<h2><a href="<?php echo $this->url('wiss/page/content', array('id' => $page->getId())) ?>"><?php echo $page->getTitle() ?></a></h2>
		<h3><?php echo $page->getLayout()->getTitle() ?> layout</h3>
		<div class="btn-group">
			<a href="<?php echo $this->url('wiss/page/properties', array('id' => $page->getId())) ?>" class="btn btn-small">Properties</a>
			<a href="<?php echo $this->url('wiss/page/route', array('id' => $page->getId())) ?>" class="btn btn-small">Route</a>
			<a href="<?php echo $this->url('wiss/page/content', array('id' => $page->getId())) ?>" class="btn btn-small">Content</a>
		</div>		
	</li>
	<?php endforeach ?>
</ul>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/page/create') ?>" class="btn btn-large btn-primary">Create new page</a>
</div>
