
<h1>Blocks</h1>

<ul class="unstyled list">
	<?php foreach($blocks as $block) : ?>
	<li class="block">
		<h2><a href="<?php echo $this->url('wiss/block/properties', array('id' => $block->getId())) ?>"><?php echo $block->getTitle() ?></a></h2>
        <h3><?php echo $block->getController() ?> : <?php echo $block->getAction() ?></h3>
        <div class="btn-group">
            <a href="<?php echo $this->url('wiss/block/properties', array('id' => $block->getId())) ?>" class="btn btn-small">Properties</a>
        </div>
	</li>
	<?php endforeach ?>
</ul>

