<h1>Modules</h1>

<?php echo $this->navigation('cms')->menu()->setMinDepth(2)->setMaxDepth(2)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs') ?>

<ul class="unstyled list">
	<?php foreach($modules as $module) : ?>
	<li>
		<h2><?php echo $module->getTitle() ?></h2>
		<a href="" class="btn btn-small">Deactivate</a>
	</li>
	<?php endforeach ?>
</ul>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/module/create') ?>" class="btn btn-large btn-primary">Create new module</a>
</div>