<h1>Modules</h1>

<?php echo $this->navigation('cms')->menu()->setMinDepth(2)->setMaxDepth(2)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs') ?>

<ul class="unstyled sortable list">
	<?php foreach($modules as $module) : ?>
	<li<?php if ($module->isLocked()) : echo ' class="locked"'; else : echo ' class="draggable"'; endif ?>>
		<h2><?php echo $module->getTitle() ?></h2>
        <?php if (!$module->isLocked()) : ?>
        <div class="btn-group">
            <a href="<?php echo $this->url('wiss/module/' . $module->getSlug() . '/properties') ?>" class="btn btn-small">Properties</a>            
            <a href="<?php echo $this->url('wiss/module/' . $module->getSlug() . '/models') ?>" class="btn btn-small">Models</a>            
            <a href="" class="btn btn-small">Deactivate</a>            
        </div>
        <?php endif ?>
	</li>
	<?php endforeach ?>
</ul>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/module/create') ?>" class="btn btn-large btn-primary">Create new module</a>
</div>