<h1><?php echo $module->getTitle() ?></h1>

<?php echo $this->navigation('cms')->menu()->setUlClass('nav nav-tabs')->renderSubmenu() ?>

<ul class="unstyled list">
	<?php foreach($models as $model) : ?>
	<li>
		<h2><?php echo $model->getTitle() ?></h2>
		<div class="btn-group">			
            <?php if($model->getNode()->getRoute()) : ?>
			<a href="<?php echo $this->url($model->getNode()->getRoute()->getFullName(), (array) $model->getNode()->getParams()) ?>" class="btn btn-small">Records</a>
            <?php endif ?>
			<a href="<?php echo $this->url('wiss/model/properties', array('slug' => $model->getSlug())) ?>" class="btn btn-small">Properties</a>
			<a href="<?php echo $this->url('wiss/model/elements', array('slug' => $model->getSlug())) ?>" class="btn btn-small">Elements</a>
		</div>
	</li>
	<?php endforeach ?>
</ul>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/model/create', array('module' => $module->getName())) ?>" class="btn btn-large btn-primary">Create new model</a>
</div>