<h1>Model <em><?php echo $model->getTitle() ?></em></h1>

<ul class="nav nav-tabs">
    <li><a href="<?php echo $this->url('wiss/model/properties', array('id' => $model->getId())) ?>">Properties</a></li>
    <li class="active"><a href="<?php echo $this->url('wiss/model/elements', array('id' => $model->getId())) ?>">Elements</a></li>
    <li><a href="<?php echo $this->url('wiss/model/export', array('id' => $model->getId())) ?>">Export</a></li>
</ul>

<ul class="unstyled">
	<?php foreach($model->getElements() as $element) : ?>
	<li>
		<h3><?php echo $element->getName() ?></h3>
		<dl class="btn-group">
			<a href="<?php echo $this->url('wiss/model/elements/configure', array('id' => $model->getId(), 'element-id' => $element->getId())) ?>" class="btn btn-small">Configure</a>
		</dl>
	</li>
	<?php endforeach ?>
</ul>

<hr>
<div>
	<h4 class="offset2">Add an element to this model</h4>
	<?php echo $this->formRenderer($form) ?>
</div>