<h1><?php echo $model->getTitle() ?></h1>

<?php echo $this->navigation('cms')->menu()->setUlClass('nav nav-tabs')->renderSubmenu() ?>

<ul class="unstyled">
	<?php foreach($model->getElements() as $element) : ?>
	<li>
		<h3><?php echo $element->getName() ?></h3>
		<dl class="btn-group">
			<a href="<?php echo $this->url('wiss/model-element/properties', array('id' => $element->getId())) ?>" class="btn btn-small">Properties</a>
			<a href="<?php echo $this->url('wiss/model-element/config', array('id' => $element->getId())) ?>" class="btn btn-small">Configuration</a>
		</dl>
	</li>
	<?php endforeach ?>
</ul>

<hr>
<div class="btn-group">
    <a href="<?php echo $this->url('wiss/model-element/create', array('model' => $model->getId())) ?>" class="btn btn-large btn-primary">Add element</a>
</div>