<h1><?php echo $model->getTitle() ?></h1>

<?php echo $this->navigation('cms')->menu()->setUlClass('nav nav-tabs')->renderSubmenu() ?>

<ul class="unstyled">
	<?php foreach($model->getElements() as $element) : ?>
	<li>
		<h3><?php echo $element->getName() ?></h3>
		<dl class="btn-group">
			<a href="<?php echo $this->url('wiss/model/elements/configure', array('id' => $model->getId(), 'element-id' => $element->getId())) ?>" class="btn btn-small">Configure</a>
		</dl>
	</li>
	<?php endforeach ?>
</ul>

<hr>
<div>
	<h4 class="offset2">Add an element to this model</h4>
	<?php echo $this->formRenderer($form) ?>
</div>