<h1>Model <em><?php echo $model->getTitle() ?></em></h1>

<ul class="nav nav-tabs">
	<?php if($model->getNode()) : ?>
    <li><a href="<?php echo $this->url($model->getNode()->getRoute()->getFullName(), (array) $model->getNode()->getParams()) ?>">Records</a></li>	
	<?php endif ?>
    <li><a href="<?php echo $this->url('wiss/model/properties', array('id' => $model->getId())) ?>">Properties</a></li>
    <li><a href="<?php echo $this->url('wiss/model/elements', array('id' => $model->getId())) ?>">Elements</a></li>
    <li class="active"><a href="<?php echo $this->url('wiss/model/export', array('id' => $model->getId())) ?>">Export</a></li>
</ul>

<p>
	Here you can choose how you export this model.
</p>
<div class="alert"><span class="label label-important">Warning</span> All previous exports will be overwritten.</div>

<?php echo $this->formRenderer($form) ?>

