<h1>Export <?php echo $model->getTitle() ?></h1>
<p>
	Here you can choose how you export this model.
</p>
<div class="alert"><span class="label label-important">Warning</span> All previous exports will be overwritten.</div>

<?php $form->prepare(); echo $this->form()->openTag($form) ?>

<?php echo $this->formElementWrapper($form->get('generate')) ?>
<?php echo $this->formElementWrapper($form->get('submit')) ?>

<?php echo $this->form()->closeTag($form) ?>

