<h1>Models</h1>

<?php echo $this->navigation('cms')->menu()->setMinDepth(2)->setMaxDepth(2)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs') ?>

<ul class="unstyled list">
	<?php foreach($models as $model) : ?>
	<li>
		<h2><a href="<?php echo $this->url('wiss/model/properties', array('slug' => $model->getSlug())) ?>"><?php echo $model->getTitle() ?></a></h2>
		<h3><?php echo $model->getEntityClass() ?></h3>
		<div class="btn-group">			
			<?php if($model->getNode()) : ?>
			<a href="<?php echo $this->url($model->getNode()->getRoute()->getFullName(), (array) $model->getNode()->getParams()) ?>" class="btn btn-primary btn-small btn-success">Records</a>
			<?php endif ?>
			<a href="<?php echo $this->url('wiss/model/properties', array('slug' => $model->getSlug())) ?>" class="btn btn-small">Properties</a>
			<a href="<?php echo $this->url('wiss/model/elements', array('slug' => $model->getSlug())) ?>" class="btn btn-small">Elements</a>
			<a href="<?php echo $this->url('wiss/model/export', array('slug' => $model->getSlug())) ?>" class="btn btn-small">Export</a>
		</div>
	</li>
	<?php endforeach ?>
</ul>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/model/create') ?>" class="btn btn-large btn-primary">Create new model</a>
</div>