<h1>Models</h1>

<?= $this->navigation('cms')->menu()->setMinDepth(2)->setMaxDepth(2)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs') ?>

<ul class="unstyled">
	<?php foreach($models as $model) : ?>
	<li>
		<h3><?= $model->getTitle() ?></h3>
		<dl>
			<a href="<?= $this->url('crud', array('name' => $model->getSlug())) ?>" class="btn btn-primary btn-small">View records</a>
			<a href="<?= $this->url('model/edit', array('id' => $model->getId())) ?>" class="btn btn-small">Edit</a>
		</dl>
	</li>
	<?php endforeach ?>
</ul>