<h1>Add new model</h1>
<p>
	<span class="label label-info">Info</span> You are about to add a new model to the system.
	With this model you can add dynamic content to the website.
	You can enter the properties below and define which form elements this model has.
</p>
<?php echo $this->form()->openTag($form) ?>

<legend>Properties</legend>
<div class="control-group well">
	<?php echo $this->formElementWrapper($form->get('title')) ?>
	<?php echo $this->formElementWrapper($form->get('entity_class')) ?>
	<?php echo $this->formElementWrapper($form->get('title_field')) ?>
</div>

<legend>Form elements</legend>
<div class="control-group">
	<ul class="unstyled list">
	<?php foreach($form->get('elements') as $element) : ?>
		<li>
			<?php echo $this->formLabel($element->get('type')) ?>
			<?php echo $this->formSelect($element->get('type')) ?>
			<?php echo $this->formButton($element->get('trigger')) ?>
		</li>
	<?php endforeach ?>
	</ul>
</div>
			
<div class="form-actions">
	<?php echo $this->formElementWrapper($form->get('submit')) ?>
</div>

<?php echo $this->form()->closeTag() ?>



<-- Modal -->
<div class="modal hide" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Configure element</h3>
    </div>
    <div class="modal-body">
        <p>Loading config form...</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary">Save changes</button>
    </div>
</div>