<h1>Add new model</h1>
<p>
	<span class="label label-info">Info</span> You are about to add a new model to the system.
	With this model you can add dynamic content to the website.
	You can enter the properties below and define which form elements this model has.
</p>
<?= $this->form()->openTag($form) ?>

<legend>Properties</legend>
<div class="control-group well">
	<?= $this->formElementWrapper($form->get('title')) ?>
	<?= $this->formElementWrapper($form->get('entity_class')) ?>
	<?= $this->formElementWrapper($form->get('title_field')) ?>
</div>

<legend>Form elements</legend>
<div class="control-group">
	<ul class="unstyled list">
	<?php foreach($form->get('elements') as $element) : ?>
		<li>
			<h2><?= $element->getOption('legend') ?></h2>
			<?php foreach($element as $child) : ?> 
			<?= $this->formRow($child) ?>
			<?php endforeach ?>		
				<a href="" class="btn btn-small">Configure</a>
		</li>
	<?php endforeach ?>
	</ul>
</div>
			
<div class="form-actions">
	<?= $this->formElementWrapper($form->get('submit')) ?>
</div>

<?= $this->form()->closeTag() ?>