<h1>List <?php echo $model->getTitle() ?></h1>

<ul class="unstyled">
	<?php foreach($entities as $entity) : ?>
	<li>
		<h3><?php echo $entity->$labelGetter() ?></h3>
		<dl>
			<?php if($model->getNavigation()) : ?>
			<?php $route = $model->getNavigation()->getRoute() ?>
			<a href="<?php echo $this->url($route->getFullName(), $route->getParams()) ?>" class="btn btn-primary btn-small">Edit</a>
			<?php endif ?>
		</dl>
	</li>
	<?php endforeach ?>
</ul>