<h1><?php echo $model->getTitle() ?></h1>

<ul class="nav nav-tabs">
	<?php if($model->getNode()) : ?>
    <li><a href="<?php echo $this->url($model->getNode()->getRoute()->getFullName(), (array) $model->getNode()->getParams()) ?>">Records</a></li>	
	<?php endif ?>
    <li class="active"><a href="<?php echo $this->url('wiss/model/properties', array('id' => $model->getId())) ?>">Properties</a></li>
    <li><a href="<?php echo $this->url('wiss/model/elements', array('id' => $model->getId())) ?>">Elements</a></li>
    <li><a href="<?php echo $this->url('wiss/model/export', array('id' => $model->getId())) ?>">Export</a></li>
</ul>

<?php echo $this->formRenderer($form) ?>
