<h1>Models</h1>

<?= $this->navigation('cms')->menu()->setMinDepth(2)->setMaxDepth(2)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs') ?>

<ul class="unstyled">
	<?php foreach($scanned as $class => $model) : ?>
	<li>
		<h3><?= $class ?></h3>
		<dl>
			<a href="<?= $this->url('model/install', array('class' => str_replace('\\', '-', $class))) ?>" class="btn btn-primary btn-small">Install</a>
		</dl>
	</li>
	<?php endforeach ?>
</ul>