<h1>Models</h1>

<?php echo $this->navigation('cms')->menu()->setMinDepth(2)->setMaxDepth(2)->setOnlyActiveBranch(true)->setUlClass('nav nav-tabs') ?>

<ul class="unstyled list">
	<?php foreach($scanned as $class => $model) : ?>
	<li>
		<h2><a href="<?php echo $this->url('wiss/model/create', array('class' => str_replace('\\', '-', $class))) ?>"><?php echo $class ?></a></h2>
		<div class="btn-group">
			<a href="<?php echo $this->url('wiss/model/create', array('class' => str_replace('\\', '-', $class))) ?>" class="btn btn-small">Install</a>
		</div>
	</li>
	<?php endforeach ?>
</ul>

<div class="btn-group">
    <a href="<?php echo $this->url('wiss/model/create') ?>" class="btn btn-large btn-primary">Create new model</a>
</div>