

<ul class="nav">
	<?php foreach ($container as $item) : ?>
	
	<?php if($item->pages) : ?>
	<li class="dropdown <?php if($item->isActive(true)) : echo 'active'; endif ?>">
		<a href="#<?php echo $item->getLabel() ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $item->getLabel() ?> <b class="caret"></b></a>
		<ul class="dropdown-menu">
			<?php foreach($item->pages as $sub) : ?>
			<li class="<?php if($sub->isActive(true)) : echo 'active'; endif ?>"><a href="<?php echo $sub->getHref() ?>"><?php echo $sub->getLabel() ?></a></li>
			<?php endforeach ?>
		</ul>
	</li>
	<?php else : ?>
	<li class="<?php if($item->isActive(true)) : echo 'active'; endif ?>"><a href="<?php echo $item->getHref() ?>"><?php echo $item->getLabel() ?></a></li>
	<?php endif ?>
	
	<?php endforeach ?>
</ul>